spring:
  datasource:
    url: jdbc:postgresql://${LIB_DB_HOST}:5432/libdb
    username: adminuser
    password: adminpswd
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers:
      - ${LIB_KAFKA_SERVER}:9092
    consumer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      auto-offset-reset: earliest

server:
  port: ${LIB_SERVER_PORT}
